application: rock-bg
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  (___.*)|
  (.*/\.svn/.*)|
  (.*/Thumbs\.db)|
  )$

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static
  static_dir: _sitestatic
  
- url: /.*
  script: djangoappengine.main.application
